### ISSUE TITLE
max() does not work on strings, head() function todo

### ISSUE THREAD

**Issue by ingomueller-net** [Sparksoniq/sparksoniq#90]
When I run the following query (against the language game dataset), Sparksoniq enters an invalid state:

    jiqs$ for $o in json-file("wasb:///sample.json")
    >>> where $o.date eq max(for $o in json-file("wasb:///sample.json") return $o.date)
    >>> return $o

After that, all queries fail with an error similar to the following one:

    [ERROR] Job aborted due to stage failure: Task 0 in stage 57.0 failed 4 times, most recent failure: Lost task 0.3 in stage 57.0 (TID 72, wn0-testsp.mjhvh3c1nveurdkkutux1zeupg.cx.internal.cloudapp.net, executor 3): java.io.IOException: org.apache.spark.SparkException: Failed to get broadcast_70_piece0 of broadcast_70

Note that the max expression cannot be evaluated. This is signaled when run on top-level:

    jiqs$ max(for $o in json-file("wasb:///sample.json") return $o.date)
    >>>
    >>>
    [ERROR] Error [err: XPTY0004]LINE:1:COLUMN:0:Max expression has non numeric args 2013-08-19

**Comment by ghislainfourny** [comment]
Here there is a bug, because max should also work on sequences of strings.

**Comment by ingomueller-net** [comment]
Then there are two bugs: the one with max on strings and the bug that I reported.

When you run the first of the two queries, Sparksoniq enters into an invalid state, in which no query cannot be evaluated anymore.

**Comment by ghislainfourny** [comment]
To summarizes, there are thus three bugs:
- max with strings
- implement the head function
- investigate why queries stop working after an invalid state is reached

**Comment by ghislainfourny** [comment]
Note: head() should work like count() as recently implemented by Can, i.e., if the parameter is an RDD, it should invoke first(). If it is not, it should materialize the input and count locally.

**Comment by CanBerker** [comment]
I have tried recreating the mentioned problem with the given query in my local environment with the sample json dataset. When I ran the two queries shown in bold below in succession, the program didn't enter an invalid state and results were returned correctly. Do you have any suggestions on what might be causing the invalid state or how I can trigger it?

jiqs$ **for $o in json-file("./src/main/resources/queries/confusion_sample.json")
 where $o.date eq max(for $o in json-file("./src/main/resources/queries/confusion_sample.json") return $o.date)
 return $o**

[ERROR] Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): sparksoniq.exceptions.UnexpectedTypeException: Error [err: XPTY0004]LINE:2:COLUMN:17:Max expression has non numeric args 2013-08-19


jiqs$ **for $o in json-file("./src/main/resources/queries/confusion_sample.json")
where $o.guess eq "Dinka"
return $o**
{ "date" : "2013-08-19", "country" : "AU", "guess" : "Dinka", "choices" : [ Danish, Dinka, Khmer, Lao ], "sample" : "af5e8f27cef9e689a070b8814dcc02c3", "target" : "Dinka" }
{ "date" : "2013-08-19", "country" : "AU", "guess" : "Dinka", "choices" : [ Amharic, Dinka, Mandarin, Yiddish ], "sample" : "cd3dffdb83f221e09710cbfbcaffdb31", "target" : "Dinka" }
{ "date" : "2013-08-19", "country" : "AU", "guess" : "Dinka", "choices" : [ Amharic, Arabic, Dinka, Samoan ], "sample" : "509c36eb58dbce009ccf93f375358d53", "target" : "Samoan" }
{ "date" : "2013-08-20", "country" : "AU", "guess" : "Dinka", "choices" : [ Dinka, Korean, Swedish, Thai ], "sample" : "0f8e6818d2be77b75712bc9ea4e87171", "target" : "Korean" }
{ "date" : "2013-08-20", "country" : "AU", "guess" : "Dinka", "choices" : [ Dinka, Malayalam, Sinhalese, Ukrainian ], "sample" : "73a09a8879e70e8648d7d75d656a5b79", "target" : "Malayalam" }
{ "date" : "2013-08-20", "country" : "AU", "guess" : "Dinka", "choices" : [ Dinka, Malayalam, Tamil, Urdu ], "sample" : "cc305dcad696147e28c6f36615aa0952", "target" : "Tamil" }
{ "date" : "2013-08-20", "country" : "AU", "guess" : "Dinka", "choices" : [ Bulgarian, Dinka, French, Khmer ], "sample" : "69a5c674fe40942aaae4d10c9df46ee0", "target" : "Bulgarian" }

[EXEC TIME]: 233

**Comment by ghislainfourny** [comment]
I think the invalid state only happens when a query has a nested FLWOR. I would simply close because we will take care of it later.

**Comment by ingomueller-net** [comment]
I cannot reproduce it myself anymore with the 0.9.4 release.

**Comment by ingomueller-net** [comment]
I tried version 0.9.2 as well and cannot reproduce it there either. Sorry that I didn't document better how to reproduce it.

**Comment by ghislainfourny** [comment]
@CanBerker I think we should go ahead and merge.
